const test = require("node:test");
const assert = require("node:assert/strict");

const fs = require("node:fs");
const path = require("node:path");

const pkg = require("../package.json");
const root = path.join(__dirname, "..");

test("the CommonJS entrypoint loads", () => {
  const lib = require("react-extension-icons");

  assert.equal(typeof lib.Icon, "object");
  assert.equal(typeof lib.getIconComponent, "function");
  assert.equal(typeof lib.PdfIconColor, "object");
});

test("the ESM entrypoint loads", async () => {
  const lib = await import("react-extension-icons");

  assert.equal(typeof lib.Icon, "object");
  assert.equal(typeof lib.getIconComponent, "function");
  assert.equal(typeof lib.PdfIconColor, "object");
});

test("a single icon can be imported without the barrel", async () => {
  const cjs = require("react-extension-icons/icons/color/PdfIconColor");
  const esm = await import("react-extension-icons/icons/color/PdfIconColor");

  assert.equal(typeof cjs.default, "object");
  assert.equal(typeof esm.default, "object");
});

test("dist module-format stubs are present", () => {
  const cjs = require(path.join(root, "dist/cjs/package.json"));
  const esm = require(path.join(root, "dist/esm/package.json"));

  assert.equal(cjs.type, "commonjs");
  assert.equal(esm.type, "module");
});

test("every path in exports and the legacy fields exists on disk", () => {
  const targets = [
    pkg.main,
    pkg.module,
    pkg.types,
    pkg.exports["."].types,
    pkg.exports["."].import,
    pkg.exports["."].require,
  ];

  for (const target of targets) {
    assert.ok(fs.existsSync(path.join(root, target)), `missing ${target}`);
  }
});

test("react is a peer dependency only", () => {
  assert.equal(pkg.dependencies, undefined, "runtime dependencies should be empty");
  assert.ok(pkg.peerDependencies.react.includes("19"), "React 19 must be supported");
  assert.ok(pkg.devDependencies.react, "React must stay a dev dependency");
});

test("the package is marked side-effect free so bundlers can tree-shake", () => {
  assert.equal(pkg.sideEffects, false);
});

test("generated sources are in sync with the generator", () => {
  // A stale checkout would publish icons that no longer match svg/.
  const generated = [
    "src/index.ts",
    "src/types/index.ts",
    "src/utils/getIconComponent.ts",
    "src/components/Icon.tsx",
  ];

  for (const file of generated) {
    const content = fs.readFileSync(path.join(root, file), "utf-8");
    assert.match(content, /^\/\/ Generated by scripts\/generateIcons\.js/, `${file} is hand-written`);
  }
});
