// Generated by scripts/generateIcons.js — do not edit by hand.
import type * as React from 'react';

export type Variant = 'color' | 'single_color' | 'grayscale';

/** Props accepted by every individual icon component. */
export interface IconSvgProps extends React.SVGProps<SVGSVGElement> {
  /** Accessible name. When omitted the icon is rendered as decorative. */
  title?: string;
  /** id for the <title> element, wired up via aria-labelledby. */
  titleId?: string;
}

export type IconComponent = React.ForwardRefExoticComponent<
  IconSvgProps & React.RefAttributes<SVGSVGElement>
>;

export interface IconProps extends Omit<IconSvgProps, 'width' | 'height'> {
  /** File extension, with or without a leading dot. Case insensitive. */
  extension: string;
  variant?: Variant;
  /** Width and height, forwarded to the svg. Defaults to 24. */
  size?: number | string;
  /** Only applied to the `single_color` variant. */
  color?: string;
}
