// Generated by scripts/generateIcons.js — do not edit by hand.
import * as React from 'react';
import type { IconProps } from '../types/index.js';
import { getIconComponent } from '../utils/getIconComponent.js';

const Icon = /* @__PURE__ */ React.forwardRef<SVGSVGElement, IconProps>(function Icon(
  { extension, variant = 'color', size = 24, color, title, ...rest },
  ref,
) {
  const IconComponent = getIconComponent(extension, variant);

  if (!IconComponent) {
    return null;
  }

  const labelled =
    title != null || rest['aria-label'] != null || rest['aria-labelledby'] != null;

  return (
    <IconComponent
      ref={ref}
      width={size}
      height={size}
      title={title}
      // Forwarding `color` on the other variants would emit a dead
      // color attribute on the <svg>.
      color={variant === 'single_color' ? color : undefined}
      aria-hidden={labelled ? undefined : true}
      focusable={false}
      {...rest}
    />
  );
});

export default Icon;
