// Generated by scripts/generateIcons.js — do not edit by hand.
import type { IconComponent, Variant } from '../types/index.js';

import AiIconColor from '../icons/color/AiIconColor.js';
import AviIconColor from '../icons/color/AviIconColor.js';
import BmpIconColor from '../icons/color/BmpIconColor.js';
import CrdIconColor from '../icons/color/CrdIconColor.js';
import CsvIconColor from '../icons/color/CsvIconColor.js';
import DllIconColor from '../icons/color/DllIconColor.js';
import DocIconColor from '../icons/color/DocIconColor.js';
import DocxIconColor from '../icons/color/DocxIconColor.js';
import DwgIconColor from '../icons/color/DwgIconColor.js';
import EpsIconColor from '../icons/color/EpsIconColor.js';
import ExeIconColor from '../icons/color/ExeIconColor.js';
import FlvIconColor from '../icons/color/FlvIconColor.js';
import GifIconColor from '../icons/color/GifIconColor.js';
import HtmlIconColor from '../icons/color/HtmlIconColor.js';
import IsoIconColor from '../icons/color/IsoIconColor.js';
import JavaIconColor from '../icons/color/JavaIconColor.js';
import JpgIconColor from '../icons/color/JpgIconColor.js';
import MdbIconColor from '../icons/color/MdbIconColor.js';
import MidIconColor from '../icons/color/MidIconColor.js';
import MovIconColor from '../icons/color/MovIconColor.js';
import Mp3IconColor from '../icons/color/Mp3IconColor.js';
import Mp4IconColor from '../icons/color/Mp4IconColor.js';
import MpegIconColor from '../icons/color/MpegIconColor.js';
import PdfIconColor from '../icons/color/PdfIconColor.js';
import PngIconColor from '../icons/color/PngIconColor.js';
import PptIconColor from '../icons/color/PptIconColor.js';
import PsIconColor from '../icons/color/PsIconColor.js';
import PsdIconColor from '../icons/color/PsdIconColor.js';
import PubIconColor from '../icons/color/PubIconColor.js';
import RarIconColor from '../icons/color/RarIconColor.js';
import RawIconColor from '../icons/color/RawIconColor.js';
import RssIconColor from '../icons/color/RssIconColor.js';
import SvgIconColor from '../icons/color/SvgIconColor.js';
import TiffIconColor from '../icons/color/TiffIconColor.js';
import TxtIconColor from '../icons/color/TxtIconColor.js';
import WavIconColor from '../icons/color/WavIconColor.js';
import WmaIconColor from '../icons/color/WmaIconColor.js';
import XmlIconColor from '../icons/color/XmlIconColor.js';
import XslIconColor from '../icons/color/XslIconColor.js';
import ZipIconColor from '../icons/color/ZipIconColor.js';
import AiIconSingleColor from '../icons/single_color/AiIconSingleColor.js';
import AviIconSingleColor from '../icons/single_color/AviIconSingleColor.js';
import BmpIconSingleColor from '../icons/single_color/BmpIconSingleColor.js';
import CrdIconSingleColor from '../icons/single_color/CrdIconSingleColor.js';
import CsvIconSingleColor from '../icons/single_color/CsvIconSingleColor.js';
import DllIconSingleColor from '../icons/single_color/DllIconSingleColor.js';
import DocIconSingleColor from '../icons/single_color/DocIconSingleColor.js';
import DocxIconSingleColor from '../icons/single_color/DocxIconSingleColor.js';
import DwgIconSingleColor from '../icons/single_color/DwgIconSingleColor.js';
import EpsIconSingleColor from '../icons/single_color/EpsIconSingleColor.js';
import ExeIconSingleColor from '../icons/single_color/ExeIconSingleColor.js';
import FlvIconSingleColor from '../icons/single_color/FlvIconSingleColor.js';
import GifIconSingleColor from '../icons/single_color/GifIconSingleColor.js';
import HtmlIconSingleColor from '../icons/single_color/HtmlIconSingleColor.js';
import IsoIconSingleColor from '../icons/single_color/IsoIconSingleColor.js';
import JavaIconSingleColor from '../icons/single_color/JavaIconSingleColor.js';
import JpgIconSingleColor from '../icons/single_color/JpgIconSingleColor.js';
import MdbIconSingleColor from '../icons/single_color/MdbIconSingleColor.js';
import MidIconSingleColor from '../icons/single_color/MidIconSingleColor.js';
import MovIconSingleColor from '../icons/single_color/MovIconSingleColor.js';
import Mp3IconSingleColor from '../icons/single_color/Mp3IconSingleColor.js';
import Mp4IconSingleColor from '../icons/single_color/Mp4IconSingleColor.js';
import MpegIconSingleColor from '../icons/single_color/MpegIconSingleColor.js';
import PdfIconSingleColor from '../icons/single_color/PdfIconSingleColor.js';
import PngIconSingleColor from '../icons/single_color/PngIconSingleColor.js';
import PptIconSingleColor from '../icons/single_color/PptIconSingleColor.js';
import PsIconSingleColor from '../icons/single_color/PsIconSingleColor.js';
import PsdIconSingleColor from '../icons/single_color/PsdIconSingleColor.js';
import PubIconSingleColor from '../icons/single_color/PubIconSingleColor.js';
import RarIconSingleColor from '../icons/single_color/RarIconSingleColor.js';
import RawIconSingleColor from '../icons/single_color/RawIconSingleColor.js';
import RssIconSingleColor from '../icons/single_color/RssIconSingleColor.js';
import SvgIconSingleColor from '../icons/single_color/SvgIconSingleColor.js';
import TiffIconSingleColor from '../icons/single_color/TiffIconSingleColor.js';
import TxtIconSingleColor from '../icons/single_color/TxtIconSingleColor.js';
import WavIconSingleColor from '../icons/single_color/WavIconSingleColor.js';
import WmaIconSingleColor from '../icons/single_color/WmaIconSingleColor.js';
import XmlIconSingleColor from '../icons/single_color/XmlIconSingleColor.js';
import XslIconSingleColor from '../icons/single_color/XslIconSingleColor.js';
import ZipIconSingleColor from '../icons/single_color/ZipIconSingleColor.js';
import AiIconGrayscale from '../icons/grayscale/AiIconGrayscale.js';
import AviIconGrayscale from '../icons/grayscale/AviIconGrayscale.js';
import BmpIconGrayscale from '../icons/grayscale/BmpIconGrayscale.js';
import CrdIconGrayscale from '../icons/grayscale/CrdIconGrayscale.js';
import CsvIconGrayscale from '../icons/grayscale/CsvIconGrayscale.js';
import DllIconGrayscale from '../icons/grayscale/DllIconGrayscale.js';
import DocIconGrayscale from '../icons/grayscale/DocIconGrayscale.js';
import DocxIconGrayscale from '../icons/grayscale/DocxIconGrayscale.js';
import DwgIconGrayscale from '../icons/grayscale/DwgIconGrayscale.js';
import EpsIconGrayscale from '../icons/grayscale/EpsIconGrayscale.js';
import ExeIconGrayscale from '../icons/grayscale/ExeIconGrayscale.js';
import FlvIconGrayscale from '../icons/grayscale/FlvIconGrayscale.js';
import GifIconGrayscale from '../icons/grayscale/GifIconGrayscale.js';
import HtmlIconGrayscale from '../icons/grayscale/HtmlIconGrayscale.js';
import IsoIconGrayscale from '../icons/grayscale/IsoIconGrayscale.js';
import JavaIconGrayscale from '../icons/grayscale/JavaIconGrayscale.js';
import JpgIconGrayscale from '../icons/grayscale/JpgIconGrayscale.js';
import MdbIconGrayscale from '../icons/grayscale/MdbIconGrayscale.js';
import MidIconGrayscale from '../icons/grayscale/MidIconGrayscale.js';
import MovIconGrayscale from '../icons/grayscale/MovIconGrayscale.js';
import Mp3IconGrayscale from '../icons/grayscale/Mp3IconGrayscale.js';
import Mp4IconGrayscale from '../icons/grayscale/Mp4IconGrayscale.js';
import MpegIconGrayscale from '../icons/grayscale/MpegIconGrayscale.js';
import PdfIconGrayscale from '../icons/grayscale/PdfIconGrayscale.js';
import PngIconGrayscale from '../icons/grayscale/PngIconGrayscale.js';
import PptIconGrayscale from '../icons/grayscale/PptIconGrayscale.js';
import PsIconGrayscale from '../icons/grayscale/PsIconGrayscale.js';
import PsdIconGrayscale from '../icons/grayscale/PsdIconGrayscale.js';
import PubIconGrayscale from '../icons/grayscale/PubIconGrayscale.js';
import RarIconGrayscale from '../icons/grayscale/RarIconGrayscale.js';
import RawIconGrayscale from '../icons/grayscale/RawIconGrayscale.js';
import RssIconGrayscale from '../icons/grayscale/RssIconGrayscale.js';
import SvgIconGrayscale from '../icons/grayscale/SvgIconGrayscale.js';
import TiffIconGrayscale from '../icons/grayscale/TiffIconGrayscale.js';
import TxtIconGrayscale from '../icons/grayscale/TxtIconGrayscale.js';
import WavIconGrayscale from '../icons/grayscale/WavIconGrayscale.js';
import WmaIconGrayscale from '../icons/grayscale/WmaIconGrayscale.js';
import XmlIconGrayscale from '../icons/grayscale/XmlIconGrayscale.js';
import XslIconGrayscale from '../icons/grayscale/XslIconGrayscale.js';
import ZipIconGrayscale from '../icons/grayscale/ZipIconGrayscale.js';

export const extensionMapping: Record<string, string> = {
  'ai': 'ai',
  'avi': 'avi',
  'bmp': 'bmp',
  'crd': 'crd',
  'csv': 'csv',
  'dll': 'dll',
  'doc': 'doc',
  'docx': 'docx',
  'dwg': 'dwg',
  'dxf': 'dwg',
  'eps': 'eps',
  'exe': 'exe',
  'flv': 'flv',
  'gif': 'gif',
  'htm': 'html',
  'html': 'html',
  'iso': 'iso',
  'jar': 'java',
  'java': 'java',
  'jfi': 'jpg',
  'jfif': 'jpg',
  'jif': 'jpg',
  'jpe': 'jpg',
  'jpeg': 'jpg',
  'jpg': 'jpg',
  'm4a': 'mp4',
  'm4p': 'mp4',
  'mdb': 'mdb',
  'mid': 'mid',
  'midi': 'mid',
  'mov': 'mov',
  'mp2': 'mpeg',
  'mp3': 'mp3',
  'mp4': 'mp4',
  'mpe': 'mpeg',
  'mpeg': 'mpeg',
  'mpg': 'mpeg',
  'mpv': 'mpeg',
  'pdf': 'pdf',
  'png': 'png',
  'potm': 'ppt',
  'potx': 'ppt',
  'ppam': 'ppt',
  'pps': 'ppt',
  'ppsm': 'ppt',
  'ppsx': 'ppt',
  'ppt': 'ppt',
  'pptx': 'ppt',
  'ps': 'ps',
  'psd': 'psd',
  'pub': 'pub',
  'qt': 'mov',
  'rar': 'rar',
  'raw': 'raw',
  'rss': 'rss',
  'sldm': 'ppt',
  'sldx': 'ppt',
  'svg': 'svg',
  'tif': 'tiff',
  'tiff': 'tiff',
  'txt': 'txt',
  'wav': 'wav',
  'wma': 'wma',
  'wmv': 'wma',
  'xml': 'xml',
  'xsl': 'xsl',
  'zip': 'zip',
};

const icons: Record<string, Partial<Record<Variant, IconComponent>>> = {
  'ai': {
    color: AiIconColor,
    single_color: AiIconSingleColor,
    grayscale: AiIconGrayscale,
  },
  'avi': {
    color: AviIconColor,
    single_color: AviIconSingleColor,
    grayscale: AviIconGrayscale,
  },
  'bmp': {
    color: BmpIconColor,
    single_color: BmpIconSingleColor,
    grayscale: BmpIconGrayscale,
  },
  'crd': {
    color: CrdIconColor,
    single_color: CrdIconSingleColor,
    grayscale: CrdIconGrayscale,
  },
  'csv': {
    color: CsvIconColor,
    single_color: CsvIconSingleColor,
    grayscale: CsvIconGrayscale,
  },
  'dll': {
    color: DllIconColor,
    single_color: DllIconSingleColor,
    grayscale: DllIconGrayscale,
  },
  'doc': {
    color: DocIconColor,
    single_color: DocIconSingleColor,
    grayscale: DocIconGrayscale,
  },
  'docx': {
    color: DocxIconColor,
    single_color: DocxIconSingleColor,
    grayscale: DocxIconGrayscale,
  },
  'dwg': {
    color: DwgIconColor,
    single_color: DwgIconSingleColor,
    grayscale: DwgIconGrayscale,
  },
  'eps': {
    color: EpsIconColor,
    single_color: EpsIconSingleColor,
    grayscale: EpsIconGrayscale,
  },
  'exe': {
    color: ExeIconColor,
    single_color: ExeIconSingleColor,
    grayscale: ExeIconGrayscale,
  },
  'flv': {
    color: FlvIconColor,
    single_color: FlvIconSingleColor,
    grayscale: FlvIconGrayscale,
  },
  'gif': {
    color: GifIconColor,
    single_color: GifIconSingleColor,
    grayscale: GifIconGrayscale,
  },
  'html': {
    color: HtmlIconColor,
    single_color: HtmlIconSingleColor,
    grayscale: HtmlIconGrayscale,
  },
  'iso': {
    color: IsoIconColor,
    single_color: IsoIconSingleColor,
    grayscale: IsoIconGrayscale,
  },
  'java': {
    color: JavaIconColor,
    single_color: JavaIconSingleColor,
    grayscale: JavaIconGrayscale,
  },
  'jpg': {
    color: JpgIconColor,
    single_color: JpgIconSingleColor,
    grayscale: JpgIconGrayscale,
  },
  'mdb': {
    color: MdbIconColor,
    single_color: MdbIconSingleColor,
    grayscale: MdbIconGrayscale,
  },
  'mid': {
    color: MidIconColor,
    single_color: MidIconSingleColor,
    grayscale: MidIconGrayscale,
  },
  'mov': {
    color: MovIconColor,
    single_color: MovIconSingleColor,
    grayscale: MovIconGrayscale,
  },
  'mp3': {
    color: Mp3IconColor,
    single_color: Mp3IconSingleColor,
    grayscale: Mp3IconGrayscale,
  },
  'mp4': {
    color: Mp4IconColor,
    single_color: Mp4IconSingleColor,
    grayscale: Mp4IconGrayscale,
  },
  'mpeg': {
    color: MpegIconColor,
    single_color: MpegIconSingleColor,
    grayscale: MpegIconGrayscale,
  },
  'pdf': {
    color: PdfIconColor,
    single_color: PdfIconSingleColor,
    grayscale: PdfIconGrayscale,
  },
  'png': {
    color: PngIconColor,
    single_color: PngIconSingleColor,
    grayscale: PngIconGrayscale,
  },
  'ppt': {
    color: PptIconColor,
    single_color: PptIconSingleColor,
    grayscale: PptIconGrayscale,
  },
  'ps': {
    color: PsIconColor,
    single_color: PsIconSingleColor,
    grayscale: PsIconGrayscale,
  },
  'psd': {
    color: PsdIconColor,
    single_color: PsdIconSingleColor,
    grayscale: PsdIconGrayscale,
  },
  'pub': {
    color: PubIconColor,
    single_color: PubIconSingleColor,
    grayscale: PubIconGrayscale,
  },
  'rar': {
    color: RarIconColor,
    single_color: RarIconSingleColor,
    grayscale: RarIconGrayscale,
  },
  'raw': {
    color: RawIconColor,
    single_color: RawIconSingleColor,
    grayscale: RawIconGrayscale,
  },
  'rss': {
    color: RssIconColor,
    single_color: RssIconSingleColor,
    grayscale: RssIconGrayscale,
  },
  'svg': {
    color: SvgIconColor,
    single_color: SvgIconSingleColor,
    grayscale: SvgIconGrayscale,
  },
  'tiff': {
    color: TiffIconColor,
    single_color: TiffIconSingleColor,
    grayscale: TiffIconGrayscale,
  },
  'txt': {
    color: TxtIconColor,
    single_color: TxtIconSingleColor,
    grayscale: TxtIconGrayscale,
  },
  'wav': {
    color: WavIconColor,
    single_color: WavIconSingleColor,
    grayscale: WavIconGrayscale,
  },
  'wma': {
    color: WmaIconColor,
    single_color: WmaIconSingleColor,
    grayscale: WmaIconGrayscale,
  },
  'xml': {
    color: XmlIconColor,
    single_color: XmlIconSingleColor,
    grayscale: XmlIconGrayscale,
  },
  'xsl': {
    color: XslIconColor,
    single_color: XslIconSingleColor,
    grayscale: XslIconGrayscale,
  },
  'zip': {
    color: ZipIconColor,
    single_color: ZipIconSingleColor,
    grayscale: ZipIconGrayscale,
  },
};

export const getIconComponent = (
  extension: string,
  variant: Variant = 'color',
): IconComponent | null => {
  const normalized = extension.trim().replace(/^\./, '').toLowerCase();
  const key = extensionMapping[normalized] ?? normalized;
  return icons[key]?.[variant] ?? null;
};
