const fs = require("fs");
const path = require("path");
const { transform } = require("@svgr/core");
const camelCase = require("lodash.camelcase");
const { optimize } = require("svgo");
const createSvgoConfig = require("../svgo.config.js");

const variants = ["color", "single_color", "grayscale"];
const root = path.join(__dirname, "..");
const svgPath = path.join(root, "svg");
const iconsPath = path.join(root, "src/icons");
const componentsPath = path.join(root, "src/components");
const typesPath = path.join(root, "src/types");
const utilsPath = path.join(root, "src/utils");
const indexPath = path.join(root, "src/index.ts");
const getIconComponentPath = path.join(utilsPath, "getIconComponent.ts");
const typesFilePath = path.join(typesPath, "index.ts");
const iconComponentPath = path.join(componentsPath, "Icon.tsx");

const BANNER = "// Generated by scripts/generateIcons.js — do not edit by hand.\n";

/**
 * extension -> icon key. Every value must resolve to an existing SVG in svg/,
 * otherwise <Icon> silently renders nothing. assertMappingIsComplete() enforces
 * that at generation time.
 */
const extensionMapping = {
  ai: "ai",
  avi: "avi",
  bmp: "bmp",
  crd: "crd",
  csv: "csv",
  dll: "dll",
  doc: "doc",
  docx: "docx",
  dwg: "dwg",
  dxf: "dwg",
  eps: "eps",
  exe: "exe",
  flv: "flv",
  gif: "gif",
  htm: "html",
  html: "html",
  iso: "iso",
  jar: "java",
  java: "java",
  jfi: "jpg",
  jfif: "jpg",
  jif: "jpg",
  jpe: "jpg",
  jpeg: "jpg",
  jpg: "jpg",
  mdb: "mdb",
  mid: "mid",
  midi: "mid",
  mov: "mov",
  mp2: "mpeg",
  mp3: "mp3",
  mp4: "mp4",
  m4a: "mp4",
  m4p: "mp4",
  mpe: "mpeg",
  mpeg: "mpeg",
  mpg: "mpeg",
  mpv: "mpeg",
  pdf: "pdf",
  png: "png",
  ppam: "ppt",
  pps: "ppt",
  ppsm: "ppt",
  ppsx: "ppt",
  ppt: "ppt",
  pptx: "ppt",
  potm: "ppt",
  potx: "ppt",
  ps: "ps",
  psd: "psd",
  pub: "pub",
  qt: "mov",
  rar: "rar",
  raw: "raw",
  rss: "rss",
  sldm: "ppt",
  sldx: "ppt",
  svg: "svg",
  tif: "tiff",
  tiff: "tiff",
  txt: "txt",
  wav: "wav",
  wma: "wma",
  wmv: "wma",
  xml: "xml",
  xsl: "xsl",
  zip: "zip",
};

const ensureDirectoriesExist = () => {
  const directories = [
    svgPath,
    iconsPath,
    componentsPath,
    typesPath,
    utilsPath,
    ...variants.map((variant) => path.join(svgPath, variant)),
    ...variants.map((variant) => path.join(iconsPath, variant)),
  ];

  directories.forEach((dir) => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });
};

/** Drop stale components so renamed/removed SVGs cannot linger in src/icons. */
const cleanGeneratedIcons = () => {
  for (const variant of variants) {
    const dir = path.join(iconsPath, variant);
    for (const file of fs.readdirSync(dir)) {
      if (file.endsWith(".tsx")) fs.unlinkSync(path.join(dir, file));
    }
  }
};

const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1);

const iconKey = (fileName) => camelCase(fileName.replace(".svg", "")).toLowerCase();

const generateComponentName = (fileName, variant) =>
  `${capitalize(camelCase(fileName.replace(".svg", "")))}Icon${capitalize(camelCase(variant))}`;

/**
 * Optimize in memory. Writing back into svg/ would destroy the source artwork
 * and makes every run depend on the previous run's output.
 */
const optimizeSvg = (filePath, prefix) => {
  const svgContent = fs.readFileSync(filePath, "utf-8");
  return optimize(svgContent, { path: filePath, ...createSvgoConfig(prefix) }).data;
};

/** The accent color the single_color artwork is drawn with. */
const ACCENT = "#5659E9";
const ACCENT_REPLACEMENT = '{props.color || "#4690FF"}';

/**
 * SVGR only matches attribute values literally, and SVGO lowercases hex colors,
 * so both spellings have to be listed or the `color` prop silently stops working.
 */
const singleColorReplacements = {
  [ACCENT]: ACCENT_REPLACEMENT,
  [ACCENT.toLowerCase()]: ACCENT_REPLACEMENT,
  currentColor: '{props.color || "currentColor"}',
};

/**
 * SVGR emits a namespace import alongside the named ones. It is unused under
 * the automatic JSX runtime and trips noUnusedLocals.
 */
const dropUnusedReactNamespaceImport = (code) =>
  /\bReact\./.test(code) ? code : code.replace(/^import \* as React from "react";\n/m, "");

/**
 * `const X = forwardRef(...)` is a top-level call, so bundlers assume it may
 * have side effects and keep every icon module alive — a single named import
 * from the barrel pulls in all 120. The annotation is what actually makes the
 * package tree-shakeable; "sideEffects": false alone does not do it.
 */
const markForwardRefAsPure = (code) =>
  code.replace(/=\s*forwardRef\(/, "= /* @__PURE__ */ forwardRef(");

const generateReactComponent = async (svgCode, componentName, variant) => {
  const code = await transform(
    svgCode,
    {
      plugins: ["@svgr/plugin-jsx"],
      typescript: true,
      icon: true,
      ref: true,
      titleProp: true,
      // We already ran SVGO with a per-component id prefix. Letting SVGR run
      // its own SVGO pass would collapse those ids back to "a".
      svgo: false,
      replaceAttrValues: variant === "single_color" ? singleColorReplacements : undefined,
    },
    { componentName }
  );

  return markForwardRefAsPure(dropUnusedReactNamespaceImport(code));
};

/** The color prop is the whole point of the single_color variant. */
const assertSingleColorIsThemeable = (componentName, code) => {
  if (!code.includes("props.color")) {
    throw new Error(
      `${componentName} has no props.color binding. The artwork probably no longer ` +
        `uses ${ACCENT}, so replaceAttrValues matched nothing.`
    );
  }
};

const generateIcons = async () => {
  const icons = { color: [], single_color: [], grayscale: [] };

  for (const variant of variants) {
    const variantPath = path.join(svgPath, variant);
    const files = fs
      .readdirSync(variantPath)
      .filter((file) => file.endsWith(".svg"))
      .sort();

    for (const file of files) {
      const componentName = generateComponentName(file, variant);
      const svgCode = optimizeSvg(path.join(variantPath, file), componentName);
      const componentCode = await generateReactComponent(svgCode, componentName, variant);

      if (variant === "single_color") {
        assertSingleColorIsThemeable(componentName, componentCode);
      }

      fs.writeFileSync(
        path.join(iconsPath, variant, `${componentName}.tsx`),
        BANNER + componentCode
      );
      icons[variant].push({ key: iconKey(file), componentName });
    }
  }

  return icons;
};

/** Every mapping target must have at least one variant, or <Icon> returns null. */
const assertMappingIsComplete = (icons) => {
  const known = new Set(variants.flatMap((v) => icons[v].map((i) => i.key)));
  const missing = [...new Set(Object.values(extensionMapping))].filter((k) => !known.has(k));

  if (missing.length > 0) {
    throw new Error(
      `extensionMapping points at icons that do not exist: ${missing.join(", ")}. ` +
        `Add the matching SVGs under svg/<variant>/ or drop the entries.`
    );
  }
};

const generateIndexFile = (icons) => {
  let content = BANNER;
  content += "export { default as Icon } from './components/Icon.js';\n";
  content += "export { getIconComponent, extensionMapping } from './utils/getIconComponent.js';\n";
  content += "export type { IconProps, IconComponent, IconSvgProps, Variant } from './types/index.js';\n\n";

  for (const variant of variants) {
    for (const { componentName } of icons[variant]) {
      content += `export { default as ${componentName} } from './icons/${variant}/${componentName}.js';\n`;
    }
  }

  fs.writeFileSync(indexPath, content);
};

const generateGetIconComponentFile = (icons) => {
  const byKey = new Map();
  for (const variant of variants) {
    for (const { key, componentName } of icons[variant]) {
      if (!byKey.has(key)) byKey.set(key, {});
      byKey.get(key)[variant] = componentName;
    }
  }
  const keys = [...byKey.keys()].sort();

  let content = BANNER;
  content += `import type { IconComponent, Variant } from '../types/index.js';\n\n`;

  for (const variant of variants) {
    for (const { componentName } of icons[variant]) {
      content += `import ${componentName} from '../icons/${variant}/${componentName}.js';\n`;
    }
  }

  content += `\nexport const extensionMapping: Record<string, string> = {\n`;
  for (const key of Object.keys(extensionMapping).sort()) {
    content += `  '${key}': '${extensionMapping[key]}',\n`;
  }
  content += `};\n\n`;

  content += `const icons: Record<string, Partial<Record<Variant, IconComponent>>> = {\n`;
  for (const key of keys) {
    content += `  '${key}': {\n`;
    for (const variant of variants) {
      const componentName = byKey.get(key)[variant];
      if (componentName) content += `    ${variant}: ${componentName},\n`;
    }
    content += "  },\n";
  }
  content += "};\n\n";

  content += `export const getIconComponent = (
  extension: string,
  variant: Variant = 'color',
): IconComponent | null => {
  const normalized = extension.trim().replace(/^\\./, '').toLowerCase();
  const key = extensionMapping[normalized] ?? normalized;
  return icons[key]?.[variant] ?? null;
};\n`;

  fs.writeFileSync(getIconComponentPath, content);
};

const generateTypesFile = () => {
  const content = `${BANNER}import type * as React from 'react';

export type Variant = 'color' | 'single_color' | 'grayscale';

/** Props accepted by every individual icon component. */
export interface IconSvgProps extends React.SVGProps<SVGSVGElement> {
  /** Accessible name. When omitted the icon is rendered as decorative. */
  title?: string;
  /** id for the <title> element, wired up via aria-labelledby. */
  titleId?: string;
}

export type IconComponent = React.ForwardRefExoticComponent<
  IconSvgProps & React.RefAttributes<SVGSVGElement>
>;

export interface IconProps extends Omit<IconSvgProps, 'width' | 'height'> {
  /** File extension, with or without a leading dot. Case insensitive. */
  extension: string;
  variant?: Variant;
  /** Width and height, forwarded to the svg. Defaults to 24. */
  size?: number | string;
  /** Only applied to the \`single_color\` variant. */
  color?: string;
}
`;

  fs.writeFileSync(typesFilePath, content);
};

const generateIconComponent = () => {
  const content = `${BANNER}import * as React from 'react';
import type { IconProps } from '../types/index.js';
import { getIconComponent } from '../utils/getIconComponent.js';

const Icon = /* @__PURE__ */ React.forwardRef<SVGSVGElement, IconProps>(function Icon(
  { extension, variant = 'color', size = 24, color, title, ...rest },
  ref,
) {
  const IconComponent = getIconComponent(extension, variant);

  if (!IconComponent) {
    return null;
  }

  const labelled =
    title != null || rest['aria-label'] != null || rest['aria-labelledby'] != null;

  return (
    <IconComponent
      ref={ref}
      width={size}
      height={size}
      title={title}
      // Forwarding \`color\` on the other variants would emit a dead
      // color attribute on the <svg>.
      color={variant === 'single_color' ? color : undefined}
      aria-hidden={labelled ? undefined : true}
      focusable={false}
      {...rest}
    />
  );
});

export default Icon;
`;

  fs.writeFileSync(iconComponentPath, content);
};

const run = async () => {
  ensureDirectoriesExist();
  cleanGeneratedIcons();
  const icons = await generateIcons();
  assertMappingIsComplete(icons);
  generateIconComponent();
  generateIndexFile(icons);
  generateGetIconComponentFile(icons);
  generateTypesFile();

  const total = variants.reduce((sum, v) => sum + icons[v].length, 0);
  console.log(`Generated ${total} icon components across ${variants.length} variants.`);
};

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
